[package]
name = "brite"
version = "0.1.0"
authors = ["Caleb Meredith <calebmeredith8@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
num = "0.2.0"
pretty = { git = "https://github.com/calebmer/pretty.rs" }
typed-arena = "1.4.1"
unicode-xid = "0.1.0"
