name: brite

dependencies:
  - base >= 4.7 && < 5
  - hspec >= 2.5 && < 3
  - text >= 1.2 && < 2
  - text-icu >= 0.7 && < 1

library:
  source-dirs: src

executables:
  brite-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - brite

tests:
  brite-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - brite
