# For advanced use and comprehensive documentation of thie file’s format, please
# see: https://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a specific stackage snapshot or a compiler version.
# A snapshot resolver dictates the compiler version and the set of packages
# to be used for project dependencies.
resolver: lts-12.22

# User packages to be built.
packages:
  - .

# Extra dependencies on top of our stackage snapshot.
extra-deps:
  # We expect these dependencies to go into LTS at some point. Delete from
  # `extra-deps` when they do.
  - containers-0.6.0.1
  - unordered-containers-0.2.10.0

# Extra directories used by stack for building
extra-include-dirs: [/usr/local/opt/icu4c/include]
extra-lib-dirs: [/usr/local/opt/icu4c/lib]
